//  Product
export const START_PRODUCTS = 'START_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

// UI
export const TOGGLE_LICENSEKEY = "TOGGLELICENSEKEY";
export const TOGGLE_NOTIFICATION = "TOGGLENOTIFICATION";
export const TRANSFER_MAIL = "TRANSFER_MAIL";

